/* Generated by Yosys 0.9+4306 (git sha1 3931b3a0, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* hdlname = "\\dom_and" *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "dom_and.v:1.1-66.10" *)
module dom_and(ClkCI, RstRI, LeftDI, RightDI, RandomDI, OutDO);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "dom_and.v:39.38-39.46" *)
  wire [8:0] BlindedD;
  (* src = "dom_and.v:43.38-43.48" *)
  wire [8:0] BufferedDN;
  (* src = "dom_and.v:44.38-44.48" *)
  reg [8:0] BufferedDP;
  (* src = "dom_and.v:5.11-5.16" *)
  input ClkCI;
  (* src = "dom_and.v:15.38-15.44" *)
  (* unused_bits = "1 2 3 5 6 7" *)
  wire [8:0] CrossD;
  (* src = "dom_and.v:7.28-7.34" *)
  input [2:0] LeftDI;
  (* src = "dom_and.v:11.29-11.34" *)
  output [2:0] OutDO;
  (* src = "dom_and.v:9.28-9.36" *)
  input [2:0] RandomDI;
  wire [7:0] RandomMapD;
  (* src = "dom_and.v:8.28-8.35" *)
  input [2:0] RightDI;
  (* src = "dom_and.v:6.11-6.16" *)
  input RstRI;
  assign _00_ = BufferedDP[1] ^ BufferedDP[0];
  assign OutDO[0] = _00_ ^ BufferedDP[2];
  assign _01_ = BufferedDP[4] ^ BufferedDP[3];
  assign OutDO[1] = _01_ ^ BufferedDP[5];
  assign _02_ = BufferedDP[7] ^ BufferedDP[6];
  assign OutDO[2] = _02_ ^ BufferedDP[8];
  assign BlindedD[0] = RightDI[0] & LeftDI[0];
  assign BlindedD[4] = LeftDI[1] & RightDI[1];
  assign BlindedD[8] = LeftDI[2] & RightDI[2];
  assign _03_ = RightDI[1] & LeftDI[0];
  assign BlindedD[1] = _03_ ^ RandomDI[0];
  assign _04_ = RightDI[2] & LeftDI[0];
  assign BlindedD[2] = _04_ ^ RandomDI[1];
  assign _05_ = LeftDI[1] & RightDI[0];
  assign BlindedD[3] = _05_ ^ RandomDI[0];
  assign _06_ = LeftDI[1] & RightDI[2];
  assign BlindedD[5] = _06_ ^ RandomDI[2];
  assign _07_ = LeftDI[2] & RightDI[0];
  assign BlindedD[6] = _07_ ^ RandomDI[1];
  assign _08_ = LeftDI[2] & RightDI[1];
  assign BlindedD[7] = _08_ ^ RandomDI[2];
  (* src = "dom_and.v:48.5-54.8" *)
  always @(posedge ClkCI, negedge RstRI)
    if (!RstRI) BufferedDP[0] <= 1'h0;
    else BufferedDP[0] <= BlindedD[0];
  (* src = "dom_and.v:48.5-54.8" *)
  always @(posedge ClkCI, negedge RstRI)
    if (!RstRI) BufferedDP[1] <= 1'h0;
    else BufferedDP[1] <= BlindedD[1];
  (* src = "dom_and.v:48.5-54.8" *)
  always @(posedge ClkCI, negedge RstRI)
    if (!RstRI) BufferedDP[2] <= 1'h0;
    else BufferedDP[2] <= BlindedD[2];
  (* src = "dom_and.v:48.5-54.8" *)
  always @(posedge ClkCI, negedge RstRI)
    if (!RstRI) BufferedDP[3] <= 1'h0;
    else BufferedDP[3] <= BlindedD[3];
  (* src = "dom_and.v:48.5-54.8" *)
  always @(posedge ClkCI, negedge RstRI)
    if (!RstRI) BufferedDP[4] <= 1'h0;
    else BufferedDP[4] <= BlindedD[4];
  (* src = "dom_and.v:48.5-54.8" *)
  always @(posedge ClkCI, negedge RstRI)
    if (!RstRI) BufferedDP[5] <= 1'h0;
    else BufferedDP[5] <= BlindedD[5];
  (* src = "dom_and.v:48.5-54.8" *)
  always @(posedge ClkCI, negedge RstRI)
    if (!RstRI) BufferedDP[6] <= 1'h0;
    else BufferedDP[6] <= BlindedD[6];
  (* src = "dom_and.v:48.5-54.8" *)
  always @(posedge ClkCI, negedge RstRI)
    if (!RstRI) BufferedDP[7] <= 1'h0;
    else BufferedDP[7] <= BlindedD[7];
  (* src = "dom_and.v:48.5-54.8" *)
  always @(posedge ClkCI, negedge RstRI)
    if (!RstRI) BufferedDP[8] <= 1'h0;
    else BufferedDP[8] <= BlindedD[8];
  assign BufferedDN = BlindedD;
  assign { CrossD[8], CrossD[4], CrossD[0] } = { BlindedD[8], BlindedD[4], BlindedD[0] };
  assign RandomMapD = { RandomDI[2:1], RandomDI[2], 1'h0, RandomDI[0], RandomDI[1:0], 1'h0 };
endmodule
